#!/usr/bin/env bash
# configures a new Ubuntu machine with respect to requirements
sudo apt-get update
sudo apt-get -y install nginx
sed -i '26 i rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
