#!/usr/bin/env bash
# displays To infinity and beyond indefinitely
#+ every 2 seconds

command=(echo "I am invincible!!!")

trap $command SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done
