#!/usr/bin/env bash
# displays To infinity and beyond indefinitely
#+ every 2 seconds and prints "I am invincible!!!"
#+ upon receiving SIGTERM

trap "echo 'I am invincible!!!'" SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done
