#!/usr/bin/env bash
#displays numbers 1-20
a=1
while [ "$a " -le 20 ]; do
    echo "$a"
    case "$a" in
	4)
	    echo "bad luck from China"
	    ;;
	9)
	    echo "bad luck from Japan"
            ;;
	17)
	    echo "bad luck from Italy"
            ;;
	esac
	let a=a+1
done
