#!/usr/bin/env bash
# set default user to nginx and listen to port 8080
pkill apache2
sed -i 's/listen 80 default_server;/listen 8080 default_server/g' /etc/nginx/sites-available/default
#sed -i 's/listen \[::\]:80 default_server ipv6only=on;/listen \[::\]:8080 default_server ipv6only=on;/g' /etc/nginx/sites-enabled/default
#sed -i 's/\#user www-data;/user nginx;/g' /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx -R
chmod 700 /etc/nginx/nginx.conf
sudo -u nginx service nginx start
