#!/usr/bin/env bash
# set default user to nginx and listen to port 8080
sed -i 's/listen 80/ listen 8080/g' /etc/nginx/sites-available/defalt
sed -i 's/\#user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sudo service nginx restart
